import React, { Component } from 'react';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <h1>Hi, I am a React App</h1>
      </div>
    );
    /**
     * Here is the equivalent using React API, which is what is generated by compiler
     */
    // return React.createElement(
    //     "div", 
    //     {className: 'App'}, 
    //     React.createElement("h1", null, "Hi from React.CreateElement()"));
  }
}
export default App;

/**
 * A React component: 
 *        class App extends Component { render() { return (<div> ... </div>); } }
 * 
 * export default App;
 *        - default export of this file (ES6): if you import this all file, you simply import the App class
 *        - used in index.js, when 
 *                    import App from './App';
 * 
 * App.js: 
 *        - could be named App.jsx
 * 
 */